version: '3.5'

services:
    minio-service:
        image: minio/minio:RELEASE.2020-11-10T21-02-24Z
        container_name: minio-service
        hostname: minio-service
        restart: unless-stopped
        volumes:
            - data:/data
        ports:
            - "4090:9000"
        networks:
            - orbis-net
        env_file: "env/${ENV}.env"
        entrypoint: sh
        command: -c 'mkdir -p /export/excel-bucket && /usr/bin/minio server /export'
        healthcheck:
          test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
          interval: 30s
          timeout: 20s
          retries: 3   
    redis:
        image: 'redis:6.0.9'
        container_name: redis
        networks:
          - orbis-net
        ports:
          - "6370:6379"
        restart: unless-stopped

volumes:
  data:

networks:
        orbis-net:
            name: orbis-network
            ipam:
                driver: default
                config:
                    - subnet: "172.16.238.0/24"
                    - subnet: "2001:3984:3989::/64"




