#build
#FROM kong:2.0.4-alpine
FROM kong:latest
USER root
MAINTAINER AAKARUI
#RUN apk update && apk add ca-certificates && rm -rf /var/cache/apk/*
#COPY ./.certi/ca.crt /usr/local/share/ca-certificates/
#COPY ./nginx_certi/* /home/kong/
#COPY ./nginx-kong.conf /usr/local/kong/nginx-kong.conf
#RUN update-ca-certificates
#USER kong
