version: '3.5'

services:
    kong-database:
        container_name: kong-database
        image: postgres:9.6
        networks:
        - orbis-net
        ports:
        - 4084:5432
        environment:
        - POSTGRES_USER=kong
        - POSTGRES_DB=kong
        - POSTGRES_PASSWORD=i6!3gV/!8aXV-q
        volumes:
        - "kong_persist_volume:/var/lib/postgresql/data"
        healthcheck:
            test: ["CMD", "pg_isready", "-U", "postgres"]
            interval: 5s
            timeout: 5s
            retries: 5
        restart: unless-stopped

    #######################################
    # Kong database migration
    #######################################
    kong-migration:
        container_name: kong-migration
        image: rosebay-kong:latest
        build:
            context: .
        networks:
        - orbis-net
        depends_on:
        - kong-database
        environment:
        - KONG_DATABASE_postgres
        - KONG_PG_HOST=kong-database
        - KONG_PG_PASSWORD=i6!3gV/!8aXV-q
        links:
        - kong-database
        command: kong migrations bootstrap
        restart: on-failure

    #######################################
    # Kong: The API Gateway
    #######################################
    kong:
        container_name: kong
        image: rosebay-kong:latest
        build:
            context: .
        networks:
        - orbis-net
        depends_on:
        - kong-database
        - kong-migration
        environment:
        - KONG_DATABASE=postgres
        - KONG_PG_HOST=kong-database
        - KONG_PG_PASSWORD=i6!3gV/!8aXV-q
        - KONG_PROXY_ACCESS_LOG=/dev/stdout
        - KONG_ADMIN_ACCESS_LOG=/dev/stdout
        - KONG_PROXY_ERROR_LOG=/dev/stderr
        - KONG_ADMIN_ERROR_LOG=/dev/stderr
        - KONG_PROXY_LISTEN=0.0.0.0:8000
        - KONG_PROXY_LISTEN_SSL=0.0.0.0:8443
        - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
        expose:
        - 8000
        - 8001
        - 8443
        - 8444
        ports:
        - "4050:8000"
        - "4052:8443"
        healthcheck:
            #test: ["CMD-SHELL", "curl -I -s -L http://127.0.0.1:8000 || exit 1"]
            test: ["CMD", "curl", "-f", "http://kong:8001"]
            interval: 5s
            timeout: 2s
            retries: 10
        restart: unless-stopped

    #######################################
    # Konga database prepare
    #######################################
    konga-prepare:
        container_name: konga-prepare
        image: pantsel/konga:next
        command: "-c prepare -a postgres -u postgresql://kong:i6%213gV%2F%218aXV-q@kong-database:5432/konga_db"
        networks:
        - orbis-net
        restart: on-failure
        links:
        - kong-database
        depends_on:
        - kong-database

    #######################################
    # Konga: Kong GUI
    #######################################
    konga:
        container_name: konga
        image: pantsel/konga:next
        restart: unless-stopped
        networks:
        - orbis-net
        environment:
            DB_ADAPTER: postgres
            DB_HOST: kong-database
            DB_USER: kong
            DB_PASSWORD: i6!3gV/!8aXV-q
            TOKEN_SECRET: km1GUr4RkcQD7DewhJPNXrCuZwcKmqjb
            DB_DATABASE: konga_db
            NODE_ENV: production
        depends_on:
        - kong-database
        ports:
        - "4051:1337"
networks:
        orbis-net:
            name: orbis-network
            ipam:
                driver: default
                config:
                    - subnet: "172.16.238.0/24"
                    - subnet: "2001:3984:3989::/64"
volumes:
        kong_persist_volume:

